# -*- coding: utf-8 -*-
"""MODUL_RIO103

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uO0i_c4FEwukq_UqC-UVerJANlijNSrV
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile rio103.py
# 
# 
# # FUNGSI 1 — PERKALIAN MATRIKS
# 
# def perkalian(A, B):
#     baris_A = len(A)
#     kolom_A = len(A[0])
#     kolom_B = len(B[0])
# 
#     hasil = [[0 for _ in range(kolom_B)] for _ in range(baris_A)]
# 
#     for i in range(baris_A):
#         for j in range(kolom_B):
#             for k in range(kolom_A):
#                 hasil[i][j] += A[i][k] * B[k][j]
# 
#     return hasil
# 
# 
# # FUNGSI 2 — TRANSPOSE MATRIKS
# 
# def transpose(A):
#     baris = len(A)
#     kolom = len(A[0])
# 
#     hasil = [[0 for _ in range(baris)] for _ in range(kolom)]
# 
#     for i in range(baris):
#         for j in range(kolom):
#             hasil[j][i] = A[i][j]
# 
#     return hasil
# 
# 
# # FUNGSI 3 — DETERMINAN MATRIKS
# 
# def determinan(A):
#     n = len(A)
# 
#     # Basis: matriks 1x1
#     if n == 1:
#         return A[0][0]
# 
#     # Basis: matriks 2x2
#     if n == 2:
#         return A[0][0] * A[1][1] - A[0][1] * A[1][0]
# 
#     # Matriks 3x3 ke atas — ekspansi kofaktor
#     det = 0
#     for j in range(n):
#         minor = [
#             [A[i][k] for k in range(n) if k != j]
#             for i in range(1, n)
#         ]
#         tanda = (-1) ** j
#         det += tanda * A[0][j] * determinan(minor)
# 
#     return det
#